version: "3.8"

services:
    nestjs:
        build: requirements/nestjs
        container_name: nestjs
        restart: always
        ports:
            - "4000:4000"
        networks:
            - transcendance_network

    nextjs:
        build: requirements/nextjs
        container_name: nextjs
        restart: always
        ports:
            - "3000:3000"
        depends_on:
            - nestjs
        networks:
            - transcendance_network

networks:
    transcendance_network:
        name: transcendance_network
