version: '3'
services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_USER: $RDS_USERNAME
      POSTGRES_PASSWORD: $RDS_PASSWORD
      POSTGRES_DB: $RDS_DB_NAME
    network_mode: "host"
    ports:
      - "5432:5432"
    

  nestjs:
    build: requirements/nestjs
    env_file:
      - ./requirements/nestjs/backend_server/backend_server/.env
    ports:
      - "4000:4000"
    container_name: nestjs
    depends_on:
      - postgresql



  nextjs:
    build: requirements/nextjs
    env_file:
      - ./requirements/nextjs/frontend/frontend/.env
    ports:
      - "3000:3000"
    container_name: nextjs
    depends_on:
      - nestjs

# version: '3'
# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_PASSWORD: ${RDS_PASSWORD}
#     ports:
#       - "5432:5432"

#   nestjs:
#     build: ./path_to_nestjs_app
#     ports:
#       - "4000:4000"
#     depends_on:
#       - postgres
#     environment:
#       CLIENT_ID: ${CLIENT_ID}
#       SECRET_KEY: ${SECRET_KEY}
#       FRONTEND: ${FRONTEND}
#       BACKEND: ${BACKEND}
#       BACKEND_PORT: ${BACKEND_PORT}

#   nextjs:
#     build: ./path_to_nextjs_app
#     ports:
#       - "3000:3000"
#     depends_on:
#       - nestjs
#     environment:
#       NEXT_PUBLIC_CLIENTID: ${NEXT_PUBLIC_CLIENTID}
#       NEXT_PUBLIC_CLIENTSECRET: ${NEXT_PUBLIC_CLIENTSECRET}
#       NEXT_PUBLIC_REDIRECTURL: ${NEXT_PUBLIC_REDIRECTURL}
#       NEXT_PUBLIC_SERVER_URL_4000: ${NEXT_PUBLIC_SERVER_URL_4000}

# version: "3.8"

# services:
#     postgresql:
#         build: requirements/postgresql/
#         container_name: postgresql
#         restart: always
#         networks:
#             - transcendance_network

#     nestjs:
#         build: requirements/nestjs
#         container_name: nestjs
#         ports:
#             - "4000:4000"
#         depends_on:
#             - postgresql
#         networks:
#             - transcendance_network

#     nextjs:
#         build: requirements/nextjs
#         container_name: nextjs
#         ports:
#             - "3000:3000"
#         depends_on:
#             - nestjs
#         networks:
#             - transcendance_network
